### ISSUE TITLE
[Bug] (iPad) YouTube's main videos screen breaks when refreshing.

### ISSUE THREAD

**Issue by RuneCE** [YTLitePlus/YTLitePlus#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.3.1
- Device model: iPad Pro (11-inch) (1st gen)
- Sideload tool (AltStore, Sideloadly, TrollStore,...): TrollStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): "v19.21.3-4.0" (edit: it happens on v19.22.6-4.0.1 too.)

### Describe the bug

When I refresh on the main screen (where all the videos are), it breaks, the whole top area becomes black, and I need to scroll down to see videos, but if I scroll too much then occasionally the bottom area is also broken.

https://github.com/YTLitePlus/YTLitePlus/assets/151409305/e7a93318-190e-4664-8837-3f4883784f16

https://github.com/YTLitePlus/YTLitePlus/assets/151409305/8c1a031b-6542-44d9-8ace-e18a929c7cb9

### Steps to reproduce the issue

1. Open the YouTube app.
2. Take your finger and swipe down to refresh.
3. Watch the entire UI break.

### Crash log (if the app crashes)

```shell
N/A
```

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

N/A

**Comment by RuneCE** [comment]
I have experimented a bit and found out that the Settings --> YouTube Plus --> Feed --> Remove ads (which is enabled by default) is causing this issue for iPad.
The issue gets progressively worse with each refresh.

**Comment by RuneCE** [comment]
@Balackburn more people are facing these issues.
My [comment above](https://github.com/YTLitePlus/YTLitePlus/issues/168#issuecomment-2151353590) has the explanation (I am fairly certain)

**Comment by RuneCE** [comment]
I will just switch to uYouEnhanced and inject the uYouPlus deb into it, as that is the best fix, does not seem they will be fixing anything here anytime soon.
For anyone else who is annoyed by these issues and wants them fixed:

Get uYouEnhanced from here: https://github.com/arichornlover/uYouEnhanced
The YTLite or YouTube Plus here: https://github.com/dayanch96/YTLite (inject with Sideloadly and export)

Then copy and paste these settings into uYouEnhanced:
`uYouAdBlockingWorkaroundLite_enabled: 0
uYouAdBlockingWorkaround_enabled: 1
removeYouTubeAds: 0
removeShortsCell: 0
hideCommunityPosts_enabled: 0`

All UI problems fixed!

**Comment by Balackburn** [comment]
> I will just switch to uYouEnhanced and inject the uYouPlus deb into it, as that is the best fix, does not seem they will be fixing anything here anytime soon.
> 
> For anyone else who is annoyed by these issues and wants them fixed:
> 
> 
> 
> Get uYouEnhanced from here: https://github.com/arichornlover/uYouEnhanced
> 
> If you want the YTLite/YouTube Plus features, get the .deb from here: https://github.com/dayanch96/YTLite (inject with Sideloadly and export)
> 
> 
> 
> Then copy and paste these in Settings -> uYouEnchanced -> "Paste Settings":
> 
> ```
> 
> uYouAdBlockingWorkaroundLite_enabled: 0
> 
> uYouAdBlockingWorkaround_enabled: 1
> 
> removeYouTubeAds: 0
> 
> removeShortsCell: 0
> 
> hideCommunityPosts_enabled: 0
> 
> ```
> 
> 
> 
> All UI problems fixed!

I don't have this issue myself, can't reproduce and it come from YTLite, I though it was fixed with 4.0, injecting the tweak in uYouEnhanced will cause the same issue

**Comment by Balackburn** [comment]
> Same issue happening in ios with latest build too

What is your device? Does the latest version (4.0.1) still cause this issue?

**Comment by emlodro** [comment]
> uYouAdBlockingWorkaroundLite_enabled: 0
> uYouAdBlockingWorkaround_enabled: 1
> removeYouTubeAds: 0
> removeShortsCell: 0
> hideCommunityPosts_enabled: 0
> ```
> 
> All UI problems fixed!

but then you get ads on the home screen, no?

**Comment by RuneCE** [comment]
> > I will just switch to uYouEnhanced and inject the uYouPlus deb into it, as that is the best fix, does not seem they will be fixing anything here anytime soon.
> > For anyone else who is annoyed by these issues and wants them fixed:
> > Get uYouEnhanced from here: https://github.com/arichornlover/uYouEnhanced
> > If you want the YTLite/YouTube Plus features, get the .deb from here: https://github.com/dayanch96/YTLite (inject with Sideloadly and export)
> > Then copy and paste these in Settings -> uYouEnchanced -> "Paste Settings":
> > ```
> > 
> > uYouAdBlockingWorkaroundLite_enabled: 0
> > 
> > uYouAdBlockingWorkaround_enabled: 1
> > 
> > removeYouTubeAds: 0
> > 
> > removeShortsCell: 0
> > 
> > hideCommunityPosts_enabled: 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > All UI problems fixed!
> 
> I don't have this issue myself, can't reproduce and it come from YTLite, I though it was fixed with 4.0, injecting the tweak in uYouEnhanced will cause the same issue

It hasn't caused me the same issue after I ran copied those 5 settings.
I can show videos of the issue still occurring on V4.0.1 of YtLitePlus - along with others having it on other devices (like iOS instead of iPadOS)

**Comment by RuneCE** [comment]
> > uYouAdBlockingWorkaroundLite_enabled: 0
> > uYouAdBlockingWorkaround_enabled: 1
> > removeYouTubeAds: 0
> > removeShortsCell: 0
> > hideCommunityPosts_enabled: 0
> > ```
> > 
> > All UI problems fixed!
> > ```
> 
> but then you get ads on the home screen, no?

No :) I haven't gotten a singular ad @emlodro nor have I gotten that issue to happen again, it seems to have completely fixed it.
If you do inject YTLite .deb into uYouEnhanced, I would suggest disabling its adblocker, just incase it overwrites with the settings you paste.

**Comment by TinTran64** [comment]
> > Same issue happening in ios with latest build too
> 
> What is your device? Does the latest version (4.0.1) still cause this issue?

I'm using the latest build on iPhone 13 pro max with iOS 17.5.1. The home screen will be blank and I'll scroll down until the content is visible again then I can scroll back up to see the contents. I used the app normally without any issues until one day it happened and I had to update to the latest version. YouTube has changed something causing this issue. Disabling ad blocking fixed the issue but I had ads all over the place(duh)

**Comment by RuneCE** [comment]
> > > Same issue happening in ios with latest build too
> > 
> > 
> > What is your device? Does the latest version (4.0.1) still cause this issue?
> 
> I'm using the latest build on iPhone 13 pro max with iOS 17.5.1. The home screen will be blank and I'll scroll down until the content is visible again then I can scroll back up to see the contents. I used the app normally without any issues until one day it happened and I had to update to the latest version. YouTube has changed something causing this issue. Disabling ad blocking fixed the issue but I had ads all over the place(duh)

Yup, had the nearly the same exact issue on iPad, only difference being that scrolling back up wouldn't fix it, only relaunching the app would.
Best solution for me has been this: https://github.com/YTLitePlus/YTLitePlus/issues/168#issuecomment-2161476574 - and maybe, eventually, YTLitePlus gets to fixing this issue.

**Comment by 42648594** [comment]
@RuneCE could you tell me exactly the relevant version numbers you used to restore functionality? Tried this with 19.24.2 decrypted IPA, currently uYouEnhanced, and the latest .deb from YTLite, pasted the settings, getting the same issue. Trying to replicate your solution to the T.

**Comment by bhackel** [comment]
Are people still having this issue? Is there anyone using iPhone instead of iPad that has this issue, or is it only iPad?
