### ISSUE TITLE
[Bug] YouTube crashing when viewing Shorts

### ISSUE THREAD

**Issue by TheNightRider12** [YTLitePlus/YTLitePlus#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.1 Dev Beta 2

### Device model

iPhone 15 Pro

### Sideload method

Signulous

### Tweak version

YTLitePlus v19.32.6 v4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When viewing the shorts tab, or trying to view shorts via the Home tab. YouTube crashes. 

### Steps to reproduce the issue

1. Load up YT Shorts via either Home or the Shorts tab
2. YouTube should crash
3. 

### Crash log (if the app crashes)

https://gist.github.com/TheNightRider12/e07ea9e2679271dff20dd1c49014be33

### Additional context

N/A

**Comment by Balackburn** [comment]
You're right, I disabled Shorts myself so I didn't have any problems after the build, use the old version for now if you want Shorts.

**Comment by ExtNinja2099** [comment]
> You're right, I disabled Shorts myself so I didn't have any problems after the build, use the old version for now if you want Shorts.

This happens on iOS 17.6.1. Shorts crashes on V19.32.6

**Comment by miketester10** [comment]
> You're right, I disabled Shorts myself so I didn't have any problems after the build, use the old version for now if you want Shorts.

How disable Shorts?

**Comment by ExtNinja2099** [comment]
> > You're right, I disabled Shorts myself so I didn't have any problems after the build, use the old version for now if you want Shorts.
> 
> How disable Shorts?

Got to settings -> Youtube Plus -> Tab bar -> Turn on Hide Shorts tab
Stay in Youtube Plus section -> In Feed -> Turn on Hide Shorts videos & Turn off Keep Shorts in Subscriptions
Close & open the app and shorts will be gone

**Comment by hauntan62** [comment]
any fix without disabling shorts yet?

**Comment by MrAlucardDante** [comment]
Same here with Youtube 19.32.8 on iOS 17.5.1

**Comment by ImmortanJo3** [comment]
Same here, crashes app on playing shorts anywhere

**Comment by JustJoostNL** [comment]
Same here too, crashes shorts in every way.

**Comment by Butterscotch96** [comment]
Same on 18.0 Public Beta 4

**Comment by patangal** [comment]
same here

**Comment by JellyPeixe** [comment]
Same here. Using YouTube V19.32.6 on iOS 17.0 with TrollStore.

**Comment by ExtNinja2099** [comment]
This issue has been fixed with latest commits from bhackel... 
The latest code works with v19.33.2

**Comment by leftbones** [comment]
The latest version on the AltStore repo is 19.32.6, hopefully the fix comes soon. I don't disable shorts because sometimes I do see something from a creator I'm familiar with that I want to check out.

**Comment by bhackel** [comment]
Temporary fix for the crash (until v5 comes out): Disable Download Manager

**Comment by MrAlucardDante** [comment]
> > Temporary fix for the crash (until v5 comes out): Disable Download Manager
> 
> 
> 
> Tried this, disabled everything under Download section yet still crashes as before when opening any kind of Shorts.

Same, it doesn't seem like that's the issue, at least on 19.32.8.

**Comment by MrAlucardDante** [comment]
After building version 19.33.2 with the latest commit from today, shorts still crashes but disabling the download manager actually fixed the issue as mentioned by bhackel

**Comment by zetix** [comment]
Disabling `Return Youtube Dislike` stops Shorts from crashing on `19.32.6`

**Comment by Rubarius** [comment]
19.32.6 -  Disabling the download manager in Youtube Plus is working.

**Comment by Velocity07** [comment]
Alright so what I did is Disable Download Manager and Return YouTube Dislike which pretty much fixed it for me, when I just disabled Return YouTube Dislike the issue came back, so try disabling both of them.

**Comment by contactmrshalin** [comment]
Download Manager is the real culprit, as shorts doesnt have Download option by Youtube, it fails to replace action there it seems

**Comment by Butterscotch96** [comment]
They could maybe add a button like uYou doesOn Aug 27, 2024, at 3:35 PM, contactmrshalin ***@***.***> wrote:﻿
Download Manager is the real culprit, as shorts doesnt have Download option by Youtube, it fails to replace action there it seems

**Comment by miketester10** [comment]
> Alright so I disabled Download Manager and Return YouTube Dislike which pretty much fixed it for me, when I just disabled Return YouTube Dislike the issue came back, so try disabling both of them.

Gotcha! Do you know if it also works on version 19.34.2?

**Comment by Velocity07** [comment]
> > Alright so I disabled Download Manager and Return YouTube Dislike which pretty much fixed it for me, when I just disabled Return YouTube Dislike the issue came back, so try disabling both of them.
> 
> Gotcha! Do you know if it also works on version 19.34.2?

Yes it does.

**Comment by bhackel** [comment]
Downloads manager is fixed in v5, and I think it may have also fixed the RYD crash. We can re-open if still having trouble
